name: house_prices_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - ipykernel
  - xgboost # 새로운 모델인 XGBoost를 위해 추가
  - openpyxl
  - pip
  - pip:
    - scikit-optimize
