name: feast_mlops_env
channels:
  - conda-forge # conda-forge를 최우선으로 설정
  - defaults
dependencies:
  - python=3.10.13        # Python 3.10의 최신 패치 버전
  - pandas=2.2.2          # Pandas 2.x 계열 최신 안정 버전
  - scikit-learn=1.3.2    # Scikit-learn 최신 안정 버전
  - joblib=1.3.2          # Joblib 최신 안정 버전
  - django=4.2.11         # Django 4.2 LTS (장기 지원) 버전의 최신 패치
  - djangorestframework=3.15.1 # Django REST Framework 최신 안정 버전
  - mlflow=2.13.0         # MLflow 최신 안정 버전
  - numpy=1.26.4          # NumPy 최신 안정 버전 (Pandas 2.2.2와 호환)
  - openpyxl=3.1.2        # OpenPyXL 최신 안정 버전
  - pyarrow=15.0.2        # PyArrow 최신 안정 버전 (Pandas, Dask와 연동)
  - sqlite=3.45.3         # SQLite 최신 안정 버전
  - dask=2024.4.0         # Dask 최신 안정 버전 (Pandas 2.x와 호환)
  - uvicorn=0.29.0        # Uvicorn 최신 안정 버전
  - redis-py=5.0.3        # Redis 클라이언트 라이브러리 (conda-forge에서 제공)
  - click=8.1.7           # Click 최신 안정 버전 (Feast 및 CLI 도구 종속성)
  - pip=24.0              # Pip 최신 안정 버전
  - pip:
    - feast==0.50.0       # Feast 최신 안정 버전 (주의: API 변경 가능성 있음)
