stages:
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/raw_data.csv
    - params.yaml
    outs:
    - model/linear_regression_model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - model/linear_regression_model.pkl
    - data/raw_data.csv
